services:
  skooli: # Main Skooli application service
    container_name: skooli-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://simon:S1m0n@postgres:5432/skooli
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - postgres
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:15
    container_name: skooli-postgres
    restart: always
    environment:
      POSTGRES_USER: simon
      POSTGRES_PASSWORD: S1m0n
      POSTGRES_DB: skooli
    ports:
      - "5432:5432" # ❗ OPTIONAL: Change if you need different port for multiple projects (e.g., "5433:5432")
    volumes:
      - skooli_postgres_data:/var/lib/postgresql/data

volumes:
  skooli_postgres_data: # Persistent storage for Skooli PostgreSQL data