FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm install

RUN npx prisma generate

COPY . .

EXPOSE 3000

# Development mode - no build needed, uses live reload
CMD ["npm", "run", "dev"]